### ISSUE TITLE
How to delete page from sitemap

### ISSUE THREAD

**Issue by niklomi** [gadicc/meteor-sitemaps#33]
I have pages that live one month. And for good seo I need to remove they from sitemap. Any advice how to do it ?

**Comment by gadicc** [comment]
Sorry for not replying to this.  I'm hoping you closed because you figured this out.  Sitemaps are generated dynamically each time the sitemap is requested, so, as soon as the page is "gone", it will no longer appear in your sitemap.  It depends of course on the function you're using to feed in the data, but assuming it's from a database query, the instant the page is no longer in the database, it's no longer in the sitemap.
